version: "3.9"

services:
  nginx:
    depends_on:
      - php
    build: ../docker/nginx
    ports:
      - "8081:80"
      - "4434:443"
    environment:
      TZ: "Europe/Moscow"
      NGINX_PORT: 80
    volumes:
      - ${SRC_PATH}:/app/www/html
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../logs/nginx:/var/log/nginx/
    networks:
      - php_nginx_internal
  php:
    build: ../docker/php8
    expose:
      - 9000
      - 9003
    volumes:
      - ${SRC_PATH}:/app/www/html
      - ../logs/php:/var/log/php
      - ../logs/xdebug:/var/log/xdebug
    environment:
      TZ: "Europe/Moscow"
    networks:
      - php_nginx_internal
  dbpostgres:
    build: ../docker/postgresql
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - ../docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - php_nginx_internal
networks:
  php_nginx_internal:
    driver: bridge


