version: "3.9"

services:
  nginx:
    depends_on:
      - php
    build: ../docker/nginx
    ports:
      - "8081:80"
      - "4434:443"
    environment:
      TZ: "Europe/Moscow"
      NGINX_PORT: 80
    volumes:
      - ../src:/app/www/html
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../logs/nginx:/var/log/nginx/
    networks:
      - php_nginx_internal
  php:
    build: ../docker/php8
    expose:
      - 9000
    volumes:
      - ../src:/app/www/html
      - ../logs/php.log:/var/log/fpm-php.www.log
    environment:
      TZ: "Europe/Moscow"
    networks:
      - php_nginx_internal
networks:
  php_nginx_internal:
    driver: bridge




